/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ExtractInterface extends ethers.utils.Interface {
  functions: {
    "getNumber()": FunctionFragment;
    "withdraw(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getNumber", values?: undefined): string;
  encodeFunctionData(functionFragment: "withdraw", values: [string]): string;

  decodeFunctionResult(functionFragment: "getNumber", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {};
}

export class Extract extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ExtractInterface;

  functions: {
    getNumber(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "getNumber()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    withdraw(
      destination: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "withdraw(address)"(
      destination: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  getNumber(overrides?: CallOverrides): Promise<BigNumber>;

  "getNumber()"(overrides?: CallOverrides): Promise<BigNumber>;

  withdraw(
    destination: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "withdraw(address)"(
    destination: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getNumber(overrides?: CallOverrides): Promise<BigNumber>;

    "getNumber()"(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      destination: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "withdraw(address)"(
      destination: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getNumber(overrides?: CallOverrides): Promise<BigNumber>;

    "getNumber()"(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      destination: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "withdraw(address)"(
      destination: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getNumber(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getNumber()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdraw(
      destination: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "withdraw(address)"(
      destination: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
